export type Material={id:string;name:string;unit:string;quantity:number;unitCost:number;notes:string};
export type Task={id:string;title:string;assignee:string;status:'todo'|'doing'|'done';priority:'low'|'normal'|'high';due:string;notes:string};
export type Channel={id:string;name:string;status:'planned'|'active'|'paused';audience:string;approach:string;notes:string};
export type Expense={id:string;date:string;name:string;category:'materials'|'postage'|'tools'|'other';amount:number;owner:string;notes:string};
export type AdEntry={id:string;date:string;channelId:string;spend:number;customers:number;notes:string};
export type Business={team:string[];principles:string;customer:string;offer:string;goals:string;materials:Material[];laborMinutes:number;hourlyRate:number;postage:number;feePercent:number;feeFixed:number;fulfillmentTargetHours:number;tasks:Task[];channels:Channel[];expenses:Expense[];ads:AdEntry[]};
export const businessDefaults:Business={team:['Reed','Carter'],principles:'Keep it simple.\nMake a sling we would use ourselves.\nBe clear about what people are getting.\nTake care of orders and answer people.',customer:'Parents buying for their kids, and teenagers who want to try slinging.',offer:'A handmade shepherd’s sling for $30. Show the product clearly and show people how to use it.',goals:'Film the how-to video.\nTake real product photos.\nFinish payment setup and get the first orders out.',materials:[{id:'cord',name:'Paracord',unit:'ft',quantity:8,unitCost:0.10,notes:'Starter estimate. Measure the cord used in one finished sling.'},{id:'leather',name:'Leather pouch + finger loop',unit:'set',quantity:1,unitCost:2.5,notes:'Starter estimate. Divide leather purchase cost by usable sets.'},{id:'packaging',name:'Packaging',unit:'set',quantity:1,unitCost:0.65,notes:'Starter estimate: mailer, label and insert.'}],laborMinutes:10,hourlyRate:15,postage:5,feePercent:3,feeFixed:0.30,fulfillmentTargetHours:48,tasks:[{id:'film-video',title:'Film and edit the how-to video',assignee:'',status:'todo',priority:'high',due:'2026-09-10',notes:''},{id:'product-photos',title:'Take real product photos',assignee:'',status:'todo',priority:'high',due:'2026-09-10',notes:''},{id:'material-costs',title:'Measure materials and replace the cost estimates',assignee:'',status:'todo',priority:'normal',due:'',notes:'Cord per sling, leather yield, packaging, and time to make one.'}],channels:[{id:'instagram',name:'Instagram',status:'planned',audience:'Teenagers and parents',approach:'Short clips of the sling, how it works, and a link to the store.',notes:''},{id:'friends',name:'Friends & word of mouth',status:'planned',audience:'People we know',approach:'Show them the sling in person. Point them to the website.',notes:''}],expenses:[],ads:[]};
const str=(v:unknown,n=2000):v is string=>typeof v==='string'&&v.length<=n;
const num=(v:unknown,max=1e7)=>typeof v==='number'&&Number.isFinite(v)&&v>=0&&v<=max;
const date=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
const items=(v:unknown,max:number,check:(x:Record<string,unknown>)=>boolean)=>Array.isArray(v)&&v.length<=max&&new Set(v.map(x=>x?.id)).size===v.length&&v.every(x=>x&&typeof x==='object'&&typeof x.id==='string'&&/^[a-zA-Z0-9_-]{1,80}$/.test(x.id)&&check(x));
export function validBusiness(v:unknown):v is Business {
 if(!v||typeof v!=='object')return false;const b=v as Business;
 return Array.isArray(b.team)&&b.team.length>0&&b.team.length<=10&&b.team.every(t=>str(t,80)&&t.trim())&&new Set(b.team).size===b.team.length
 &&[b.principles,b.customer,b.offer,b.goals].every(s=>str(s,10000))
 &&[b.laborMinutes,b.hourlyRate,b.postage,b.feeFixed].every(n=>num(n,10000))&&num(b.feePercent,100)&&num(b.fulfillmentTargetHours,8760)&&b.fulfillmentTargetHours>0
 &&items(b.materials,100,m=>str(m.name,120)&&str(m.unit,40)&&num(m.quantity,10000)&&num(m.unitCost,10000)&&str(m.notes))
 &&items(b.tasks,500,t=>str(t.title,300)&&!!t.title.trim()&&str(t.assignee,80)&&['todo','doing','done'].includes(String(t.status))&&['low','normal','high'].includes(String(t.priority))&&(t.due===''||date(t.due))&&str(t.notes))
 &&items(b.channels,100,c=>str(c.name,120)&&!!c.name.trim()&&['planned','active','paused'].includes(String(c.status))&&str(c.audience)&&str(c.approach)&&str(c.notes))
 &&items(b.expenses,2000,e=>date(e.date)&&str(e.name,200)&&['materials','postage','tools','other'].includes(String(e.category))&&num(e.amount)&&str(e.owner,80)&&str(e.notes))
 &&items(b.ads,2000,a=>date(a.date)&&b.channels.some(c=>c.id===a.channelId)&&num(a.spend)&&num(a.customers)&&Number.isInteger(a.customers)&&str(a.notes));
}
export function unitCosts(b:Business,price:number){const materials=b.materials.reduce((s,m)=>s+m.quantity*m.unitCost,0),labor=b.laborMinutes/60*b.hourlyRate,cogs=materials+labor,fees=price*b.feePercent/100+b.feeFixed;return {materials,labor,cogs,fees,contribution:price-cogs-fees-b.postage};}
