import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const origin='http://127.0.0.1:8787';
const owner={'Origin':origin,'oai-authenticated-user-id':'local-editor','oai-authenticated-user-email':'editor@example.test'};
const get=path=>fetch(origin+path);
const save=(body,headers=owner)=>fetch(origin+'/api/content',{method:'PUT',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(body)});
const initial=await (await get('/api/content')).json();
assert.equal((await (await get('/api/editor')).json()).canEdit,false);
assert.equal((await save(initial,{})).status,403);
assert.equal((await save(initial,{...owner,'oai-authenticated-user-email':'visitor@example.test'})).status,403);
assert.equal((await save(initial,{...owner,Origin:'https://example.com'})).status,403);
assert.equal((await save({...initial,content:{...initial.content,price:-1}})).status,400);
assert.equal((await save({...initial,content:{...initial.content,instagram:'javascript:alert(1)'}})).status,400);
const image=await fs.readFile('public/images/river-stones.jpg');
assert.equal((await fetch(origin+'/api/media',{method:'POST',body:image})).status,403);
assert.equal((await fetch(origin+'/api/media',{method:'POST',headers:owner,body:'<svg>bad</svg>'})).status,400);
const uploaded=await fetch(origin+'/api/media',{method:'POST',headers:owner,body:image});assert.equal(uploaded.status,201);const {src}=await uploaded.json();
const served=await get(src);assert.equal(served.status,200);assert.equal(served.headers.get('content-type'),'image/jpeg');assert.deepEqual(Buffer.from(await served.arrayBuffer()),image);
const content=structuredClone(initial.content);content.copy['home.made-for-a-good-time']='Saved editor check';content.media.photos.reverse();content.media.hero=src;content.price=32.50;content.sections.reverse();
const response=await save({...initial,content});assert.equal(response.status,200);const saved=await response.json();
const reread=await (await get('/api/content')).json();assert.deepEqual(reread,saved);assert.equal((await save({...initial,content})).status,409);
const restore=await save({revision:saved.revision,content:initial.content});assert.equal(restore.status,200);
const spa=await get('/studio');assert.equal(spa.status,200);assert.match(spa.headers.get('content-type'),/html/);
console.log('Passed: owner-only editing, cross-origin rejection, validation, image upload + retrieval, durable content, stale-tab protection, restore, and SPA routing.');
